#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/Applications/NEURON-7.7/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/Applications/NEURON-7.7/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/Users/frankmazza/frankm/LFPy/mod/x86_64/.libs/libnrnmech.so" "$@"
